services:
  postgres:
    image: postgres
    restart: always
    container_name: docker-postgres
    volumes:
      - ./local_database/data:/var/lib/postgresql/data
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres

  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080
